name: Deploy Actions

# Prerequisite: secret 'DATAMINER_DEPLOY_KEY' necessary on Repository or Organization level.
# Value is the API-key generated in the DCP Admin app (https://admin.dataminer.services/) as authentication for a certain DataMiner System.

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: []
    tags:
      - "[0-9]+.[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+.[0-9]+-**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  LAB_CD:   
    name: Staging CD
    environment: staging
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3

       - name: Skyline DataMiner Deploy Action Development
         uses: SkylineCommunications/Skyline-DataMiner-Deploy-Action@v1
         with:
           # Stage deploy
           stage: All
           # The API-key: generated in the DCP Admin app (https://admin.dataminer.services/) as authentication for a certain DataMiner System.
           api-key: ${{ secrets.LAB_DEPLOY_KEY }}
           solution-path: ./Number-Format-Display.sln
           artifact-name: ${{ github.repository }} ${{ github.ref_name }}_B${{ github.run_number }}
           build-number: ${{ github.run_number }}
